server:
  port: 8501

nacos:
  config:
    server-addr: 127.0.0.1:8848 #nacos的serverAdd配置
    group: NAOCS-SPRING-CLOUD-GATEWAY #分组的配置
    file-extension: json
    data-id: spring-cloud-gateway.json #data-id的配置

